name: Desplegar a Firebase Hosting

on:
  push:
    branches:
      - main # Cambia esto por tu rama principal si usas "master" u otra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # (Opcional) Agrega aquí tus pasos de compilación si tu app los requiere, como:
      # - name: Instalar dependencias
      #   run: npm install
      # - name: Compilar proyecto
      #   run: npm run build

      - name: Desplegar a Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
